my_tuple=()
print(my_tuple)
my_tuple=(1,2,3)
print(my_tuple)
my_tuple=(1,"hello",2.8)
print(my_tuple)
n_tuple=("mouse",[8,6,4],(1,2,3))
print(my_tuple)
print(n_tuple[0][3])
print(n_tuple[1][1])
print("sliced:",my_tuple[1:4])
for letter in(my_tuple):
    print("hello",letter)